// --- SVG Helpers ---
// We use overlapping blobs to represent the 'dogs' or 'cars'
const svgBase = `
    <svg viewBox="0 0 400 400" class="w-full h-full shadow-lg bg-white rounded-xl" id="canvas-svg">
        <!-- Grid background -->
        <defs>
            <pattern id="smallGrid" width="20" height="20" patternUnits="userSpaceOnUse">
                <path d="M 20 0 L 0 0 0 20" fill="none" stroke="#f1f5f9" stroke-width="1"/>
            </pattern>
        </defs>
        <rect width="400" height="400" fill="url(#smallGrid)" rx="12" />

        <!-- Bounding Boxes -->
        <rect id="box-1" x="40" y="50" width="160" height="180" class="box-outline" rx="8" />
        <rect id="box-2" x="180" y="140" width="180" height="150" class="box-outline" rx="8" />
        <rect id="box-3" x="80" y="240" width="160" height="130" class="box-outline" rx="8" />

        <!-- Shapes (Dogs/Cars) -->
        <!-- Dog 1 -->
        <path id="shape-1" class="dog-shape" d="M 60 100 C 60 60, 180 60, 180 140 C 180 200, 100 220, 60 180 Z" />
        <!-- Dog 2 -->
        <path id="shape-2" class="dog-shape" d="M 200 160 C 250 120, 340 140, 340 220 C 340 280, 220 290, 200 240 Z" />
        <!-- Dog 3 -->
        <path id="shape-3" class="dog-shape" d="M 100 260 C 120 220, 220 250, 220 320 C 220 380, 80 370, 100 260 Z" />

        <!-- Labels -->
        <text id="label-class" x="200" y="40" text-anchor="middle" class="blob-text text-3xl font-black fill-slate-800 tracking-widest">DOGS!</text>
        <text id="label-1" x="120" y="145" text-anchor="middle" class="blob-text text-xl font-bold fill-white">Dog 1</text>
        <text id="label-2" x="270" y="210" text-anchor="middle" class="blob-text text-xl font-bold fill-white">Dog 2</text>
        <text id="label-3" x="155" y="315" text-anchor="middle" class="blob-text text-xl font-bold fill-white">Dog 3</text>
    </svg>
`;

const pixelGridBase = `
    <div class="grid grid-cols-6 gap-1 p-2 bg-slate-200 rounded-xl w-full max-w-sm aspect-square shadow-inner relative" id="pixel-grid">
        <!-- Generated by JS -->
    </div>
    <div id="scanner-line" class="absolute top-0 left-0 w-full h-2 bg-blue-400/50 blur-sm hidden"></div>
`;

const realWorldBase = `
    <div class="flex flex-col gap-6 w-full fade-in">
        <div class="bg-white p-6 rounded-xl shadow-md border-l-4 border-blue-500 flex items-center gap-6">
            <div class="bg-blue-100 p-4 rounded-full text-blue-600 text-3xl"><i class="fa-solid fa-car-side"></i></div>
            <div>
                <h4 class="font-bold text-lg text-slate-800">Self-Driving Cars</h4>
                <p class="text-sm text-slate-500 mt-1">Tracks individual pedestrians to predict specific movements, rather than seeing a big "blob" of people.</p>
            </div>
        </div>
        <div class="bg-white p-6 rounded-xl shadow-md border-l-4 border-green-500 flex items-center gap-6 mt-4">
            <div class="bg-green-100 p-4 rounded-full text-green-600 text-3xl"><i class="fa-solid fa-apple-whole"></i></div>
            <div>
                <h4 class="font-bold text-lg text-slate-800">Farming Robotics</h4>
                <p class="text-sm text-slate-500 mt-1">Robot arms need to identify exactly where one apple ends and another begins to pick them without crushing.</p>
            </div>
        </div>
    </div>
`;

// --- Data & Steps Definition ---
const steps = [
    {
        title: "1. The Raw Image",
        text: "<p>Imagine you have a coloring book page with a picture of three dogs playing in a park.</p><p>To the AI initially, this is just a blank canvas with lines. It doesn't know what these shapes mean yet.</p>",
        visualType: "svg",
        action: () => {
            document.querySelectorAll('.dog-shape').forEach(el => { el.style.fill = 'transparent'; el.style.stroke = '#4b5563'; });
            document.querySelectorAll('.box-outline').forEach(el => el.style.opacity = '0');
            document.querySelectorAll('.blob-text').forEach(el => el.style.opacity = '0');
        }
    },
    {
        title: "2. Image Classification",
        text: "<p>Image Classification is like looking at the page and shouting, <strong>\"Dogs!\"</strong></p><p>The AI knows what is in the picture, but it has no idea <em>where</em> they are or <em>how many</em> there are.</p>",
        visualType: "svg",
        action: () => {
            document.querySelectorAll('.dog-shape').forEach(el => { el.style.fill = 'transparent'; el.style.stroke = '#4b5563'; });
            document.querySelectorAll('.box-outline').forEach(el => el.style.opacity = '0');
            document.querySelectorAll('.blob-text').forEach(el => el.style.opacity = '0');
            document.getElementById('label-class').style.opacity = '1';
        }
    },
    {
        title: "3. Object Detection",
        text: "<p>Object Detection is like drawing a big square box around each dog with a pencil.</p><p>Now the AI knows <strong>where</strong> they are and <strong>how many</strong> there are, but the boxes include a lot of background (like the grass they are standing on).</p>",
        visualType: "svg",
        action: () => {
            document.querySelectorAll('.dog-shape').forEach(el => { el.style.fill = 'transparent'; el.style.stroke = '#4b5563'; });
            document.getElementById('label-class').style.opacity = '0';
            document.querySelectorAll('.blob-text:not(#label-class)').forEach(el => el.style.opacity = '0');
            document.querySelectorAll('.box-outline').forEach(el => el.style.opacity = '1');
        }
    },
    {
        title: "4. Semantic Segmentation",
        text: "<p>Semantic Segmentation is if you take a brown crayon and color exactly inside the lines of <em>all</em> the dogs.</p><p>Now you have a giant brown blob. You know exactly where dog pixels are, but <strong>you can't tell where one dog ends and another begins!</strong></p>",
        visualType: "svg",
        action: () => {
            document.querySelectorAll('.box-outline').forEach(el => el.style.opacity = '0');
            document.getElementById('label-class').style.opacity = '0';
            document.querySelectorAll('.blob-text:not(#label-class)').forEach(el => el.style.opacity = '0');
            document.querySelectorAll('.dog-shape').forEach(el => {
                el.style.fill = '#8B4513'; // Brown blob
                el.style.stroke = 'transparent';
            });
        }
    },
    {
        title: "5. Instance Segmentation",
        text: "<p>Instance Segmentation (the goal) is when you color the first dog <strong>blue</strong>, the second <strong>green</strong>, and the third <strong>red</strong>.</p><p>You colored perfectly inside the lines, AND you know exactly how many there are and which one is which!</p>",
        visualType: "svg",
        action: () => {
            document.getElementById('label-class').style.opacity = '0';
            document.querySelectorAll('.box-outline').forEach(el => el.style.opacity = '0');

            const colors = ['#3b82f6', '#22c55e', '#ef4444']; // Blue, Green, Red
            document.querySelectorAll('.dog-shape').forEach((el, index) => {
                el.style.fill = colors[index];
                el.style.stroke = 'transparent';
            });

            document.getElementById('label-1').style.opacity = '1';
            document.getElementById('label-2').style.opacity = '1';
            document.getElementById('label-3').style.opacity = '1';
        }
    },
    {
        title: "6. How it Works: The Scout",
        text: "<p>To achieve this, CNNs (like <strong>Mask R-CNN</strong>) use a two-step trick.</p><p><strong>Step 1: Find the Box (The Scout).</strong> The AI scans the image and guesses where objects might be, drawing bounding boxes.</p>",
        visualType: "svg",
        action: () => {
            // Reset to just boxes and outlines to show the 'Scout' phase
            document.querySelectorAll('.blob-text').forEach(el => el.style.opacity = '0');
            document.querySelectorAll('.dog-shape').forEach(el => { el.style.fill = 'transparent'; el.style.stroke = '#94a3b8'; });

            // Highlight the boxes one by one via CSS
            const boxes = document.querySelectorAll('.box-outline');
            boxes.forEach(el => { el.style.opacity = '0'; el.style.stroke = '#ef4444'; });

            setTimeout(() => { boxes[0].style.opacity = '1'; }, 300);
            setTimeout(() => { boxes[1].style.opacity = '1'; }, 900);
            setTimeout(() => { boxes[2].style.opacity = '1'; }, 1500);
        }
    },
    {
        title: "7. The Artist & The Math",
        text: "<p><strong>Step 2: Color the Shape (The Artist).</strong> The AI zooms into ONE box and looks at a grid of pixels.</p><p>It calculates a probability score $P$ for each pixel $(i,j)$ inside that box using this formula:</p>",
        math: "P(y_{i,j} = \\text{Car}) = \\sigma(w \\cdot x + b)",
        visualType: "grid",
        action: () => {
            generateGrid(false);
        }
    },
    {
        title: "8. Applying the Threshold",
        text: "<p>If $P > 0.5$ (more than a 50% chance), the AI says: <em>\"Yes, this pixel is part of the car! Color it blue!\"</em></p><p>If $P \\le 0.5$, the AI says: <em>\"No, this is just background road. Leave it dark.\"</em></p><p>By doing this instantly for thousands of pixels inside the box, it perfectly separates the instances!</p>",
        math: "\\text{Color Pixel} = \\begin{cases} \\text{Blue}, & \\text{if } P > 0.5 \\\\ \\text{Gray}, & \\text{if } P \\le 0.5 \\end{cases}",
        visualType: "grid",
        action: () => {
            generateGrid(true); // Animate the thresholding
        }
    },
    {
        title: "9. Real World Importance",
        text: "<p>Why do we need such specific mathematical exactness in AI?</p><p>If you don't separate the instances, robots and vehicles can make catastrophic mistakes by treating a group of objects as one solid wall.</p>",
        visualType: "realworld",
        action: () => {
            // Nothing to script, static HTML handles it
        }
    }
];

let currentStep = 0;

// --- DOM Elements ---
const btnNext = document.getElementById('btn-next');
const btnBack = document.getElementById('btn-back');
const titleEl = document.getElementById('step-title');
const descEl = document.getElementById('step-description');
const mathContainer = document.getElementById('math-container');
const visualContainer = document.getElementById('visual-container');
const progressBar = document.getElementById('progress-bar');
const currentStepLabel = document.getElementById('current-step-label');
const totalStepLabel = document.getElementById('total-step-label');

totalStepLabel.innerText = steps.length;

// --- Grid Generation Logic (For Steps 7 & 8) ---
function generateGrid(applyThreshold = false) {
    visualContainer.innerHTML = pixelGridBase;
    const gridEl = document.getElementById('pixel-grid');
    gridEl.innerHTML = ''; // clear

    // Shape of a car in a 6x6 grid (1 = object, 0 = background)
    const carShape = [
        0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0,
        1, 1, 1, 1, 1, 1,
        0, 1, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0
    ];

    carShape.forEach((isCar, index) => {
        const cell = document.createElement('div');
        cell.className = 'pixel-cell flex items-center justify-center rounded text-[10px] md:text-xs font-mono font-bold text-slate-400 bg-white shadow-sm border border-slate-100';

        // Add noise to make it look like probabilities
        let prob;
        if (isCar) {
            prob = (Math.random() * 0.4 + 0.55).toFixed(2); // 0.55 to 0.95
        } else {
            prob = (Math.random() * 0.4 + 0.05).toFixed(2); // 0.05 to 0.45
        }

        cell.innerText = prob;

        if (applyThreshold) {
            // Add slight delay based on index for scanner effect
            setTimeout(() => {
                if (parseFloat(prob) > 0.5) {
                    cell.classList.remove('bg-white', 'text-slate-400');
                    cell.classList.add('bg-blue-500', 'text-white', 'shadow-blue-200');
                } else {
                    cell.classList.remove('bg-white');
                    cell.classList.add('bg-slate-300', 'text-slate-500', 'opacity-50');
                }
            }, index * 40); // 40ms stagger
        }

        gridEl.appendChild(cell);
    });

    if (applyThreshold) {
        const scanner = document.getElementById('scanner-line');
        scanner.classList.remove('hidden');
        scanner.style.animation = "scanDown 1.5s linear forwards";

        // inject keyframe dynamically
        if (!document.getElementById('scan-style')) {
            const style = document.createElement('style');
            style.id = 'scan-style';
            style.innerHTML = `@keyframes scanDown { 0% { top: 0; opacity: 1; } 90% { opacity: 1; } 100% { top: 100%; opacity: 0; } }`;
            document.head.appendChild(style);
        }
    }
}

// --- Render Function ---
function renderStep(stepIndex) {
    const step = steps[stepIndex];

    // Text & Animations
    titleEl.innerHTML = step.title;

    // Trigger animation re-flow
    const textContent = document.getElementById('text-content');
    textContent.classList.remove('slide-up');
    void textContent.offsetWidth; // trigger reflow
    textContent.classList.add('slide-up');

    // Parse inline LaTeX wrapped in $ $
    const processedText = step.text.replace(/\$(.*?)\$/g, (match, math) => {
        try {
            return katex.renderToString(math, { throwOnError: false, displayMode: false });
        } catch (e) {
            return match;
        }
    });
    descEl.innerHTML = processedText;

    // Math Rendering (KaTeX)
    if (step.math) {
        mathContainer.classList.remove('hidden');
        katex.render(step.math, mathContainer, { displayMode: true, throwOnError: false });
    } else {
        mathContainer.classList.add('hidden');
        mathContainer.innerHTML = '';
    }

    // Visual Rendering
    if (step.visualType === "svg") {
        if (!document.getElementById('canvas-svg')) {
            visualContainer.innerHTML = svgBase;
        }
    } else if (step.visualType === "realworld") {
        visualContainer.innerHTML = realWorldBase;
    }

    // Execute specific logic for the step
    setTimeout(() => { step.action(); }, 50);

    // UI Updates
    progressBar.style.width = `${((stepIndex + 1) / steps.length) * 100}%`;
    currentStepLabel.innerText = stepIndex + 1;

    btnBack.disabled = stepIndex === 0;
    if (stepIndex === steps.length - 1) {
        btnNext.disabled = true;
        btnNext.innerHTML = 'Finish <i class="fa-solid fa-check ml-2"></i>';
        btnNext.classList.replace('bg-blue-600', 'bg-green-600');
        btnNext.classList.replace('hover:bg-blue-700', 'hover:bg-green-700');
    } else {
        btnNext.disabled = false;
        btnNext.innerHTML = 'Next <i class="fa-solid fa-arrow-right ml-2"></i>';
        btnNext.classList.replace('bg-green-600', 'bg-blue-600');
        btnNext.classList.replace('hover:bg-green-700', 'hover:bg-blue-700');
    }
}

// --- Event Listeners ---
btnNext.addEventListener('click', () => {
    if (currentStep < steps.length - 1) {
        currentStep++;
        renderStep(currentStep);
    }
});

btnBack.addEventListener('click', () => {
    if (currentStep > 0) {
        currentStep--;
        renderStep(currentStep);
    }
});

// Initialize First Step
renderStep(currentStep);